### ISSUE TITLE
OSL Glass - Bump doesn't work

### ISSUE THREAD

**Issue by juancarlosgzrz** [appleseedhq/appleseed-max#132] opened 2018-03-02 21:36 UTC
This is in normal mode, not in 'use max procs'.

**Comment by usakhelo** [comment] 2018-03-03 03:21
It doesn't work correctly or doesn't work at all?
In my version it works, and I remember in your beta it worked too. Try to increase the amount may be.

![image](https://user-images.githubusercontent.com/1850877/36930080-0dd323ae-1e68-11e8-837d-789cc03f7a18.png)

**Comment by juancarlosgzrz** [comment] 2018-03-04 07:56
Then scales between osl and use max procs are way to different

**Comment by usakhelo** [comment] 2018-03-04 08:34
That's different issue.

**Comment by dictoon** [comment] 2018-03-04 12:10
Indeed, if @juancarlosgzrz you confirm that with a different scale, bump works for you then we can close this one and open a new ticket to investigate why different modes require such different scales (which is a problem, I agree).

**Comment by juancarlosgzrz** [comment] 2018-03-04 20:46
Working! Sometimes I get 'bugs' that I can't reproduce, it's weird. 

![image](https://user-images.githubusercontent.com/26150363/36950382-f5c7f5d0-1fa9-11e8-8eb6-b44337863710.png)

**Closed** 2018-03-04 20:46 UTC
Labels: Bug

**Comment by dictoon** [comment] 2018-03-07 07:42
Nice!

> Sometimes I get 'bugs' that I can't reproduce, it's weird.

The vast majority of real bugs should be entirely reproducible, at least on the same machine (i.e. there's little true randomness in appleseed, the only one is caused by multithreaded rendering).
