### ISSUE TITLE
Random tiles ignored when rendering

### ISSUE THREAD

**Issue by juancarlosgzrz** [appleseedhq/appleseed-max#131] opened 2018-02-22 19:10 UTC

**Comment by usakhelo** [comment] 2018-03-04 20:22
I'm able to replicate this issue in release build of .studio, final rendering.
Attached are project archive and saved image.
Bug doesn't show up on each rendering, but if I render several times I definitely get missing tiles, sometimes more sometimes less.

![image001](https://user-images.githubusercontent.com/1850877/36950134-85dba756-1fbf-11e8-9a1b-ae184dd4048a.png)
[test_missing_tiles.zip](https://github.com/appleseedhq/appleseed-max/files/1778904/test_missing_tiles.zip)

**Comment by usakhelo** [comment] 2018-03-04 20:23
![image](https://user-images.githubusercontent.com/1850877/36950168-0bb1c41e-1fc0-11e8-954a-855f5bc069e4.png)

**Comment by juancarlosgzrz** [comment] 2018-03-04 21:18
I don't, I think yours are differente related bug. The bug I refered to is when I get total black tiles, material independant.

**Comment by dictoon** [comment] 2018-03-04 22:08
@usakhelo When that happens, do you have any particular message in the log panel? Warnings or errors?

**Comment by dictoon** [comment] 2018-03-04 22:29
Sadly I cannot reproduce either using appleseed.studio from `master` branch in Release mode.

**Comment by usakhelo** [comment] 2018-03-05 05:05
Nothing unusual in log panel.
I'm getting missing tiles on two different machines. Strange that you can't reproduce. I have to run render several times though.. May be not great way to reproduce something.

**Comment by dictoon** [comment] 2018-03-07 07:46
This is really weird, I've never seen this problem. Is it only happening with OSL materials? How's the frequency of it happening varying with the number of threads? Does it happen with only 4, 2 or even 1 thread? Does it happen with only 1 spp?

I don't recall if you're building appleseed yourself or not, I think you are. If you are, you could try with a debug build of appleseed. It will be much slower but maybe you'll catch something.

**Comment by usakhelo** [comment] 2018-03-08 05:07
It happens on subsurface osl material, when Profile is `Better Dipole`. This is how it looks sometimes:
![image](https://user-images.githubusercontent.com/1850877/37133828-8ea2ebf0-2263-11e8-94a0-7629b2990032.png)

I've tried with one thread (set CPU cores to 1 in max plugin) and I coudn't get missing tiles again. 
But I got different look several times, much less frequently:
![image](https://user-images.githubusercontent.com/1850877/37133978-3a15520c-2264-11e8-8c9d-218ee6ceb65f.png)

On debug it happens less frequently, probably never seen on debug build. I can't reproduce it in studio on debug build.

**Comment by dictoon** [comment] 2018-03-08 07:10
Does it _only_ happen with OSL SSS? What about non-OSL SSS?

**Comment by dictoon** [comment] 2018-03-08 07:12
> But I got different look several times, much less frequently

That looks like it's entirely missing the BSSRDF part of the material. So it would not be _missing tiles_, it's just that some tiles (in fact, some entire threads) don't consider the BSSRDF at all, or fail to sample it.

**Comment by usakhelo** [comment] 2018-03-10 04:42
I only that bug only with sss materials.

**Comment by juancarlosgzrz** [comment] 2018-03-13 23:10
I don't know how to replicate the original general bug. The one when I get totally black tiles, as if it were ditching pixels. It only appears once in a while and it's more frequent on my 12 threads pc than my 4 threads pc work.

**Comment by Mango-3** [comment] 2018-09-18 13:51
Seems like it only happens with the uniform pixel sampler.
With the adaptive tile sampler I haven't seen this bug.

**Comment by juancarlosgzrz** [comment] 2018-11-12 20:32
Correct, mango. Even though the bug is still there with the uniform pixel sampler

**Comment by dictoon** [comment] 2018-11-12 21:08
Frang also found out that the bigger the tile size, the more likely tiles are gonna be missing. Can you guys confirm that?

What I'm planning to do at some point when I have time (but feel free to steal the idea and do it yourself) is to wrap the Max plugin's tile callbacks with try/catch and write a log message if any exception occurs. I have the feeling that there's some kind of exception that kills the tile callback.

**Comment by juancarlosgzrz** [comment] 2018-11-12 21:11
I'll try with bigger tile sizes. Remember we are talking about two different bugs in this thread: SSS and general rendering black tiles.

**Comment by dictoon** [comment] 2019-01-30 22:42
Fixed in ab4667267b6d38ff8ac5c5066d452ee9649f9167.

**Closed by dictoon** 2019-01-30 22:42 UTC
Labels: Bug
